#!/bin/bash

if [ -f "./config.env" ]; then
    echo "Reading config.env file"
    source "./config.env"
fi

docker stop erps_instance
docker rm erps_instance
docker run -p 10026:10026 -d --name erps_instance --restart="always" --env ENABLE_LOG=${ENABLE_LOG} --env API_KEY=${API_KEY} tirinox/erudite_push_stream

if [ "$ENABLE_LOG" != "" ]; then
    docker logs -f erps_instance
fi