#!/bin/sh
docker stop erps_instance
docker rm erps_instance
docker run -p 10026:10026 -d --name erps_instance --restart="always" --env ENABLE_LOG=1 tirinox/erudite_push_stream
docker logs -f erps_instance
